### PR TITLE
Update to work with latest zellij release

### PR DESCRIPTION
**Pull request by Zshoham**
* adapted to the API changes in 0.41.2
* fixed clippy lints
* print plugin names in for actions that use plugins

### CODE REVIEW

**Comment by karimould** [comment]
Thank you very much, ill check it tomorrow :-)

**Review by karimould — APPROVED** [review]

**Comment by karimould** [comment]
thank you

**Comment by Zshoham** [comment]
Hey, I saw that you merged and released a new version. 
But I think you might have uploaded the debug version to the release page (its 51MB,
and when I build a release version locally its a more reasonable 1.1MB).

**Comment by karimould** [comment]
you are totally right :-) thanks again. 
I updated the release.

**Comment by Zshoham** [comment]
My pleasure, great work with the plugin !

**Pull request merged**
